name: Publish Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Write Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true